<?php

namespace app\src\models;

use app\src\filters\BookSearch;
use app\src\traits\Filterable;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

/**
 * This is the model class for table "book".
 *
 * @property int $id
 * @property string|null $title
 * @property string $article
 * @property string|null $date_receipt
 * @property bool|null $status
 *
 * @property Author[] $authors
 */
class Book extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return 'book';
    }

    public function rules()
    {
        return [
            [['article'], 'required'],
            [['date_receipt'], 'safe'],
            [['title', 'article'], 'string', 'max' => 255],
            [['article'], 'unique'],
        ];
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;
        return $this;
    }

    public function setArticle(): self
    {
        $this->article = Yii::$app->security->generateRandomString(30);
        return $this;
    }

    public function setDateReceipt(): self
    {
        $this->date_receipt =  date('Y-m-d H:i:s');
        return $this;
    }

    public static function find()
    {
        return (new BookSearch($_GET))->apply(parent::find()); // TODO: Change the autogenerated stub
    }

    public function setStatus(bool $status){
        $this->status = $status;
        return $this;
    }

    public function getAuthors()
    {
        return $this->hasMany(Author::class, ['id' => 'author_id'])->viaTable(
            'book_author', ['book_id' => 'id']
        );
    }

    public function fields()
    {
        $fields = parent::fields();
        $fields['date_receipt'] = function (){
          return  Yii::$app->formatter->asDatetime($this->date_receipt, 'd M Y');
        };
        $fields['authors'] = function (){
          return $this->authors;
        };
        return $fields;
    }

    public function extraFields()
    {
        return [
          'authors'
        ];
    }
}
